@api = http://localhost:3001

GET {{api}}/products 

###

GET {{api}}/product/6358b89979c1d9fe6a0f35d8 

### 

POST {{api}}/products 
Content-Type: application/json

{
  "name": "CBD Face Cream 300mg",
  "images": ["https://byolitic.com/wp-content/uploads/2021/06/CBD-face-cream-30ml-300x300.png"],
  "type": "Crema",
  "description": "El mejor del mercado",
  "price": 1190
}

###

POST {{api}}/users/login 
Content-Type: application/json

{
  "email": "pablo@gmail.com",
  "password": "1234asdf"
}

###

POST {{api}}/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXJjaGFzZXMiOltdLCJfaWQiOiI2MzVjOGM0NDJhNjFlNGFmZDdhMjM3MzkiLCJuYW1lIjoiUGFibG8iLCJlbWFpbCI6InBhYmxvQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJDBuTGdBbEw2QnFWOGZxT2NWcGsyeWU4NnNHaHZTQUF6Z2dyL1JQUGs2Sk9CRk8vU0ZWY2k2IiwiZmF2b3JpdGVzIjpbXSwiaXNBZG1pbiI6ZmFsc2UsImNyZWF0ZWRBdCI6IjIwMjItMTAtMjlUMDI6MTM6MjQuNDY5WiIsInVwZGF0ZWRBdCI6IjIwMjItMTAtMjlUMDI6MTM6MjQuNDY5WiIsImlhdCI6MTY2NzM5NTI3M30.KuTdxF8ooyJjhBJU3Y-lPFKQh4lmnqPNXT_AUxoLN74"
}

###

DELETE {{api}}/users/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXJjaGFzZXMiOltdLCJfaWQiOiI2MzVjOGM0NDJhNjFlNGFmZDdhMjM3MzkiLCJuYW1lIjoiUGFibG8iLCJlbWFpbCI6InBhYmxvQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJDBuTGdBbEw2QnFWOGZxT2NWcGsyeWU4NnNHaHZTQUF6Z2dyL1JQUGs2Sk9CRk8vU0ZWY2k2IiwiZmF2b3JpdGVzIjpbXSwiaXNBZG1pbiI6ZmFsc2UsImNyZWF0ZWRBdCI6IjIwMjItMTAtMjlUMDI6MTM6MjQuNDY5WiIsInVwZGF0ZWRBdCI6IjIwMjItMTAtMjlUMDI6MTM6MjQuNDY5WiIsImlhdCI6MTY2NzQzMjY1MH0.j0_qV63JTT6eVZ7OGhIJK_x5hHQTrmwYBGkV27CyHoI"
}


###
/*
  "name": "Natural CBD Oil Drops 1000mg in 30ml",
  "images": ["https://byolitic.com/wp-content/uploads/2021/07/CBD-Oil-Drops-1000mg-300x300.png"],
  "type": "Aceite",

  "name": "Citrus CBD Coconut Oil 1000mg in 30ml",
  "images": ["https://byolitic.com/wp-content/uploads/2021/06/CBD-Oil-Citrus-300x300.png"],
  "type": "Aceite",
  
  "name": "CBD Face Cream 500mg",
  "images": ["https://byolitic.com/wp-content/uploads/2021/06/CBD-face-cream-30ml-300x300.png"],
  "type": "Crema",

  "name": "Green CBD Gummies 25mg",
  "images": ["https://byolitic.com/wp-content/uploads/2021/06/CBD-gummy-squares-1-300x300.png"],
  "type": "Gomitas",

  "name": "CBD Pills Mint Flavour 20mg",
  "images": ["https://byolitic.com/wp-content/uploads/2021/06/cbd-mint-pills-1-300x300.png"],
  "type": "Pildoras",
*/



